import React from 'react';
import styled, { keyframes } from 'styled-components';
import AutoAwesomeRoundedIcon from '@mui/icons-material/AutoAwesomeRounded';
import Searchbar from '../components/Searchbar';
import Imagecard from '../components/Imagecard';

const Container = styled.div`
  height: 100%;
  overflow-y: scroll;
  padding: 30px 30px;
  padding-bottom:50px;
  display:flex;
  flex-direction :column;
  align-items:center;
  gap:20px;
  @media(max-width:768px){
  padding:6px 10px;
  }


  &::-webkit-scrollbar {
    display: none;
  }
  -ms-overflow-style: none;
  scrollbar-width: none;
`;

 const Headline=styled.div`
 font-size:28px;;
 color: ${({ theme }) => theme.text_primary};
 display:flex;
 flex-direction :column;
 align-items:center;
   @media(max-width:600px){
   font-size:22px;;
  }
`;

const gradientAnimation = keyframes`
  0% {
    background-position: 0% 0%;
  }
  50% {
    background-position: 100% 100%;
  }
  100% {
    background-position: 0% 0%;
  }
`;

const Span = styled.div`
  font-size: 30px;
  font-weight: 600;
  background: linear-gradient(45deg, #ff6f61, #ffcc70, #8e44ad, #3498db);
  background-size: 400% 400%;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  animation: ${gradientAnimation} 5s ease infinite;
  @media(max-width:768px){
  padding:6px 10px;
  }
`;

const Wrapper=styled.div`
width:100%
max-width:1400px;
padding:32px 0px;
display:flex;
justify-content:center;
`;

const CardWrapper = styled.div`
  display: grid;
  gap: 20px;
  @media (min-width: 1200px) {
    grid-template-columns: repeat(4, 1fr);
  }
  @media (min-width: 640px) and (max-width: 1199px) {
    grid-template-columns: repeat(3, 1fr);
  }
  @media (max-width: 639px) {
    grid-template-columns: repeat(2, 1fr);
  }
`;



const Home = () => {
  return (
    <Container>
    <Headline>See the Top Community Favorites!</Headline>
    <Span>Generated by AI <AutoAwesomeRoundedIcon/></Span>
    <Searchbar/>
    <Wrapper>
      <CardWrapper>
        <Imagecard/>
        <Imagecard/>
        <Imagecard/>
        <Imagecard/>
        <Imagecard/>
        <Imagecard/>
        <Imagecard/>
      </CardWrapper>
    </Wrapper>
    </Container>
  );
};

export default Home;
